backend:
  name: github
  repo: magicmyco/magicmyco.github.io # Path to your GitHub repository
  branch: main

media_folder: "docs/assets/images/" # Media files will be stored in the repo under images/uploads

collections:
  - name: "mushroom_grow_guide" # Used in routes, e.g., /admin/collections/blog
    label: "Mushroom Grow Guide" # Used in the UI
    folder: "docs/_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    nested:
      depth: 100 # max depth to show in the collection tree
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }

